# Generated by Django 5.2.4 on 2026-01-10 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('BATSMAN', 'Batsman'), ('BOWLER', 'Bowler'), ('ALL_ROUNDER', 'All Rounder'), ('WICKET_KEEPER', 'Wicket Keeper')], max_length=20)),
                ('batting_hand', models.CharField(choices=[('RIGHT', 'Right Hand'), ('LEFT', 'Left Hand')], default='RIGHT', max_length=20)),
                ('bowling_style', models.CharField(blank=True, choices=[('FAST', 'Fast'), ('SPIN', 'Spin'), ('MEDIUM', 'Medium')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=10, unique=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('match_type', models.CharField(choices=[('T20', 'T20'), ('ODI', 'ODI'), ('TEST', 'Test')], default='T20', max_length=10)),
                ('is_live', models.BooleanField(default=False)),
                ('match_ended', models.BooleanField(default=False)),
                ('opt_to', models.CharField(blank=True, choices=[('BAT', 'Bat'), ('BOWL', 'Bowl')], max_length=10, null=True)),
                ('current_innings', models.IntegerField(default=1)),
                ('teams', models.ManyToManyField(related_name='matches', to='simulator.team')),
                ('toss_won_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toss_wins', to='simulator.team')),
            ],
        ),
        migrations.CreateModel(
            name='PlayingSquad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_captain', models.BooleanField(default=False)),
                ('is_wicket_keeper', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squads', to='simulator.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.team')),
            ],
            options={
                'unique_together': {('match', 'player')},
            },
        ),
    ]
