# Generated by Django 5.2.4 on 2026-01-10 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innings', models.IntegerField()),
                ('over_number', models.IntegerField()),
                ('ball_number', models.IntegerField()),
                ('runs_batter', models.IntegerField(default=0)),
                ('extras', models.IntegerField(default=0)),
                ('total_runs', models.IntegerField(default=0)),
                ('is_wide', models.BooleanField(default=False)),
                ('is_no_ball', models.BooleanField(default=False)),
                ('is_bye', models.BooleanField(default=False)),
                ('is_leg_bye', models.BooleanField(default=False)),
                ('is_wicket', models.BooleanField(default=False)),
                ('dismissal_type', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bowler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balls_bowled', to='simulator.player')),
                ('dismissed_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dismissals', to='simulator.player')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balls', to='simulator.match')),
                ('non_striker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balls_at_non_striker', to='simulator.player')),
                ('striker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balls_faced', to='simulator.player')),
            ],
        ),
        migrations.CreateModel(
            name='BattingScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innings', models.IntegerField()),
                ('runs', models.IntegerField(default=0)),
                ('balls_faced', models.IntegerField(default=0)),
                ('fours', models.IntegerField(default=0)),
                ('sixes', models.IntegerField(default=0)),
                ('strike_rate', models.FloatField(default=0.0)),
                ('is_out', models.BooleanField(default=False)),
                ('dismissal_text', models.CharField(blank=True, max_length=100, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_scores', to='simulator.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.player')),
            ],
            options={
                'unique_together': {('match', 'player', 'innings')},
            },
        ),
        migrations.CreateModel(
            name='BowlingScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innings', models.IntegerField()),
                ('overs', models.FloatField(default=0.0)),
                ('maidens', models.IntegerField(default=0)),
                ('runs_conceded', models.IntegerField(default=0)),
                ('wickets', models.IntegerField(default=0)),
                ('economy', models.FloatField(default=0.0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowling_scores', to='simulator.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.player')),
            ],
            options={
                'unique_together': {('match', 'player', 'innings')},
            },
        ),
        migrations.CreateModel(
            name='InningsScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innings', models.IntegerField()),
                ('total_runs', models.IntegerField(default=0)),
                ('total_wickets', models.IntegerField(default=0)),
                ('total_overs', models.FloatField(default=0.0)),
                ('extra_runs', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_declared', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innings_scores', to='simulator.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.team')),
            ],
            options={
                'unique_together': {('match', 'team', 'innings')},
            },
        ),
    ]
