# Generated by Django 5.2.4 on 2026-01-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_ball_battingscore_bowlingscore_inningsscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='battingscore',
            name='is_on_strike',
            field=models.BooleanField(default=False),
        ),
    ]
