# Generated by Django 5.2.4 on 2026-01-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0003_battingscore_is_on_strike'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='seconds_per_ball',
            field=models.FloatField(default=1.0),
        ),
    ]
