# Generated by Django 5.2.4 on 2026-01-20 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0004_match_seconds_per_ball'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='venue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='batting_style',
            field=models.CharField(blank=True, help_text='Technical attributes', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='batting_type',
            field=models.CharField(blank=True, help_text='Technical attributes', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='bowling_hand',
            field=models.CharField(choices=[('RIGHT', 'Right Hand'), ('LEFT', 'Left Hand'), ('UNKNOWN', 'Unknown')], default='RIGHT', max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='bowling_type',
            field=models.CharField(blank=True, help_text='Pace/Spin variations', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='fielding_skill',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10),
        ),
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.FloatField(blank=True, help_text='Height in cm', null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='height_type',
            field=models.CharField(blank=True, help_text='Short/Medium/Tall', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='nick_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight in kg', null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='wicket_keeping_skill',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='batting_hand',
            field=models.CharField(choices=[('RIGHT', 'Right Hand'), ('LEFT', 'Left Hand'), ('UNKNOWN', 'Unknown')], default='RIGHT', max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulator.nationality'),
        ),
    ]
