# Generated by Django 5.2.4 on 2026-02-04 12:56

from django.db import migrations


def backfill_tournament(apps, schema_editor):
    Tournament = apps.get_model('simulator', 'Tournament')
    Match = apps.get_model('simulator', 'Match')

    tournament, _ = Tournament.objects.get_or_create(
        code="tour123",
        defaults={"name": "IPL"},
    )

    Match.objects.filter(tournament__isnull=True).update(tournament=tournament)


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0006_tournament_match_tournament'),
    ]

    operations = [
        migrations.RunPython(backfill_tournament, migrations.RunPython.noop),
    ]
